# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache .gradle/caches
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Cache .gradle/wrapper
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

   #

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ClimbableChain Artifact
        path: build/libs/*.jar

    - name: Get info from gradle
      id: get_info
      run: |
        VERSION=`grep version build.gradle | grep '=' | grep -Eo \'.*\' | grep -Eo '[a-z|A-Z|0-9|.|_]*'`
        NAME=`grep "rootProject.name" settings.gradle | grep -Eo \'.*\' | grep -Eo '[a-z|A-Z|0-9|.|_]*'`
        FILE_PATH="./build/libs/"$NAME"-"$VERSION".jar"
        FILE_NAME=$NAME"-"$VERSION".jar"
        VERSION=$VERSION.`git rev-parse --short HEAD`
        echo ::set-output name=file_path::$FILE_PATH
        echo ::set-output name=file_name::$FILE_NAME
        echo ::set-output name=version::$VERSION

    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: Release_${{steps.get_info.outputs.version}}
        release_name: Release ${{steps.get_info.outputs.version}}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
      with:
        asset_path: ${{steps.get_info.outputs.file_path}}
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_name: ${{steps.get_info.outputs.file_name}}
        asset_content_type: application/java-archive
